[package]
name = "mr-accuracy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruint = "1.4.0"
plotters = "0.3.4"